package com.hospital.service.impl;

import com.hospital.dto.*;
import com.hospital.entity.*;
import com.hospital.repository.*;
import com.hospital.service.PortalService;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

@Service
public class PortalServiceImpl implements PortalService {
    private final DiagnosticTestRepository diagnosticTestRepository; private final TestBookingRepository testBookingRepository;
    private final TestResultRepository testResultRepository; private final BloodInventoryRepository bloodInventoryRepository;
    private final BloodRequestRepository bloodRequestRepository; private final BedRepository bedRepository;
    private final BedBookingRepository bedBookingRepository; private final PatientRepository patientRepository;
    private final AppointmentRepository appointmentRepository; private final PaymentRepository paymentRepository;
    private final ContactMessageRepository contactMessageRepository;

    public PortalServiceImpl(DiagnosticTestRepository diagnosticTestRepository, TestBookingRepository testBookingRepository, TestResultRepository testResultRepository, BloodInventoryRepository bloodInventoryRepository, BloodRequestRepository bloodRequestRepository, BedRepository bedRepository, BedBookingRepository bedBookingRepository, PatientRepository patientRepository, AppointmentRepository appointmentRepository, PaymentRepository paymentRepository, ContactMessageRepository contactMessageRepository) {
        this.diagnosticTestRepository = diagnosticTestRepository; this.testBookingRepository = testBookingRepository; this.testResultRepository = testResultRepository; this.bloodInventoryRepository = bloodInventoryRepository; this.bloodRequestRepository = bloodRequestRepository; this.bedRepository = bedRepository; this.bedBookingRepository = bedBookingRepository; this.patientRepository = patientRepository; this.appointmentRepository = appointmentRepository; this.paymentRepository = paymentRepository; this.contactMessageRepository = contactMessageRepository;
    }
    public List<DiagnosticTestDto> listDiagnosticTests() { return diagnosticTestRepository.findByActiveTrueOrderByCategoryAscNameAsc().stream().map(this::toTestDto).toList(); }
    @Transactional public DiagnosticTestDto saveDiagnosticTest(DiagnosticTestDto dto) { DiagnosticTest test = dto.getId() == null ? new DiagnosticTest() : diagnosticTestRepository.findById(dto.getId()).orElseThrow(() -> new IllegalStateException("Diagnostic test not found")); test.setName(dto.getName()); test.setCategory(dto.getCategory()); test.setDescription(dto.getDescription()); test.setPreparationInstructions(dto.getPreparationInstructions()); test.setEstimatedProcessingTime(dto.getEstimatedProcessingTime()); test.setActive(dto.isActive()); return toTestDto(diagnosticTestRepository.save(test)); }
    @Transactional public TestBookingDto bookTest(User user, TestBookingRequest request) { Patient patient = patient(user); DiagnosticTest test = diagnosticTestRepository.findByIdForUpdate(request.getDiagnosticTestId()).filter(DiagnosticTest::isActive).orElseThrow(() -> new IllegalStateException("This diagnostic test is unavailable")); if (request.getBookingTime().toLocalTime().isBefore(LocalTime.of(9, 0)) || !request.getBookingTime().toLocalTime().isBefore(LocalTime.of(17, 0))) throw new IllegalStateException("Select a test slot between 9:00 and 17:00"); if (testBookingRepository.existsByDiagnosticTestIdAndBookingTimeAndStatusNot(test.getId(), request.getBookingTime(), "CANCELLED")) throw new IllegalStateException("This test slot is no longer available"); return toBookingDto(testBookingRepository.save(TestBooking.builder().patient(patient).diagnosticTest(test).bookingTime(request.getBookingTime()).status("BOOKED").build())); }
    public List<TestBookingDto> listMyTestBookings(User user) { return testBookingRepository.findByPatientOrderByBookingTimeDesc(patient(user)).stream().map(this::toBookingDto).toList(); }
    public List<TestResultDto> listMyTestResults(User user) { return testResultRepository.findByPatientOrderByResultedAtDesc(patient(user)).stream().map(result -> TestResultDto.builder().id(result.getId()).testName(result.getDiagnosticTest().getName()).category(result.getDiagnosticTest().getCategory()).status(result.getStatus()).resultSummary(result.getResultSummary()).reportUrl(result.getReportUrl()).resultedAt(result.getResultedAt()).build()).toList(); }
    public List<BloodInventoryDto> listBloodInventory() { return bloodInventoryRepository.findAll().stream().map(this::toBloodDto).toList(); }
    @Transactional public BloodInventoryDto saveBloodInventory(BloodInventoryDto dto) { if (dto.getAvailableUnits() < 0) throw new IllegalStateException("Available blood units cannot be negative"); BloodInventory inventory = dto.getId() == null ? bloodInventoryRepository.findByBloodGroup(dto.getBloodGroup()).orElseGet(BloodInventory::new) : bloodInventoryRepository.findById(dto.getId()).orElseThrow(() -> new IllegalStateException("Blood inventory record not found")); inventory.setBloodGroup(normalizeGroup(dto.getBloodGroup())); inventory.setAvailableUnits(dto.getAvailableUnits()); inventory.setUpdatedAt(Instant.now()); return toBloodDto(bloodInventoryRepository.save(inventory)); }
    @Transactional public BloodRequestDto requestBlood(User user, BloodRequestDto dto) { String group = normalizeGroup(dto.getBloodGroup()); BloodInventory inventory = bloodInventoryRepository.findByBloodGroupForUpdate(group).orElseThrow(() -> new IllegalStateException("Blood group is not available")); if (dto.getQuantity() > inventory.getAvailableUnits()) throw new IllegalStateException("Requested quantity exceeds available blood inventory"); inventory.setAvailableUnits(inventory.getAvailableUnits() - dto.getQuantity()); inventory.setUpdatedAt(Instant.now()); bloodInventoryRepository.save(inventory); BloodRequest request = bloodRequestRepository.save(BloodRequest.builder().patient(patient(user)).bloodGroup(group).quantity(dto.getQuantity()).status("REQUESTED").build()); dto.setId(request.getId()); dto.setBloodGroup(group); dto.setStatus(request.getStatus()); return dto; }
    @Transactional public BedBookingDto reserveBed(User user, BedBookingRequest request) { Bed bed = bedRepository.findByIdForUpdate(request.getBedId()).orElseThrow(() -> new IllegalStateException("Bed not found")); if (bed.getStatus() != BedStatus.VACANT) throw new IllegalStateException("This bed is no longer available"); bed.setStatus(BedStatus.RESERVED); Ward ward = bed.getWard(); ward.setReservedBeds(ward.getReservedBeds() + 1); BedBooking booking = bedBookingRepository.save(BedBooking.builder().patient(patient(user)).bed(bed).requestedFrom(request.getRequestedFrom()).status("RESERVED").notes(request.getNotes()).build()); return BedBookingDto.builder().id(booking.getId()).bedId(bed.getId()).bedNumber(bed.getBedNumber()).wardName(ward.getWardName()).requestedFrom(booking.getRequestedFrom()).status(booking.getStatus()).build(); }
    public List<MedicalRecordDto> listMedicalRecords(User user) { Patient patient = patient(user); boolean hasPaymentRecords = paymentRepository.findByPatient(patient).stream().anyMatch(payment -> payment.getAmount() != null); return appointmentRepository.findByPatient(patient).stream().map(item -> MedicalRecordDto.builder().appointmentId(item.getId()).appointmentTime(item.getAppointmentTime()).doctorName(item.getDoctor().getUser().getFirstName() + " " + item.getDoctor().getUser().getLastName()).department(item.getDoctor().getDepartment() == null ? "Not provided" : item.getDoctor().getDepartment().getName()).diagnosis(item.getDiagnosis()).status(item.getStatus()).billedAmount(null).billingStatus(hasPaymentRecords ? "Payment records exist; ask billing for appointment-level details" : "No billing information available").build()).toList(); }
    @Transactional public UUID saveContactMessage(ContactMessageRequest request) { return contactMessageRepository.save(ContactMessage.builder().name(request.getName().trim()).email(request.getEmail().trim().toLowerCase()).phone(request.getPhone()).subject(request.getSubject().trim()).message(request.getMessage().trim()).build()).getId(); }
    private Patient patient(User user) { return patientRepository.findByUser(user).orElseThrow(() -> new IllegalStateException("Patient profile required")); }
    private DiagnosticTestDto toTestDto(DiagnosticTest test) { return DiagnosticTestDto.builder().id(test.getId()).name(test.getName()).category(test.getCategory()).description(test.getDescription()).preparationInstructions(test.getPreparationInstructions()).estimatedProcessingTime(test.getEstimatedProcessingTime()).active(test.isActive()).build(); }
    private TestBookingDto toBookingDto(TestBooking booking) { return TestBookingDto.builder().id(booking.getId()).diagnosticTestId(booking.getDiagnosticTest().getId()).testName(booking.getDiagnosticTest().getName()).category(booking.getDiagnosticTest().getCategory()).bookingTime(booking.getBookingTime()).status(booking.getStatus()).build(); }
    private BloodInventoryDto toBloodDto(BloodInventory inventory) { int units = inventory.getAvailableUnits(); return BloodInventoryDto.builder().id(inventory.getId()).bloodGroup(inventory.getBloodGroup()).availableUnits(units).availabilityStatus(units == 0 ? "Out of Stock" : units < 5 ? "Limited" : "Available").build(); }
    private String normalizeGroup(String group) { String value = group == null ? "" : group.trim().toUpperCase(); if (!List.of("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-").contains(value)) throw new IllegalStateException("Select a valid blood group"); return value; }
}
