import { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Container, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import BloodtypeIcon from '@mui/icons-material/Bloodtype';
import { BloodInventory, getBloodInventory, requestBlood } from '../services/portal';
import { EmptyState, LoadingState } from '../components/PageState';

const groups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
const BloodBankPage = () => { const [inventory, setInventory] = useState<BloodInventory[]>([]); const [loading, setLoading] = useState(true); const [group, setGroup] = useState(''); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => { setLoading(true); getBloodInventory().then((r) => setInventory(r.data)).catch(() => setError('Unable to load blood inventory.')).finally(() => setLoading(false)); }; useEffect(load, []);
  const submit = async () => { setError(''); setMessage(''); try { await requestBlood(group, quantity); setMessage('Blood request submitted and inventory updated. The hospital will confirm fulfilment.'); load(); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to submit the blood request.'); } };
  if (loading) return <Container maxWidth="lg"><LoadingState label="Checking blood inventory…" /></Container>;
  const selected = inventory.find((item) => item.bloodGroup === group);
  return <Container maxWidth="lg" sx={{ py: 5 }}><Stack direction="row" spacing={1} alignItems="center"><BloodtypeIcon color="error" /><Typography variant="h4" component="h1">Blood bank</Typography></Stack><Typography color="text.secondary" sx={{ mb: 3 }}>Inventory is managed by the hospital. Donor information is never displayed.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{message && <Alert severity="success" sx={{ mb: 2 }}>{message}</Alert>}{inventory.length === 0 ? <EmptyState>Blood inventory has not been published by the hospital.</EmptyState> : <Grid container spacing={2}>{groups.map((bloodGroup) => { const item = inventory.find((entry) => entry.bloodGroup === bloodGroup); return <Grid item xs={6} sm={3} key={bloodGroup}><Card><CardContent><Typography variant="h5">{bloodGroup}</Typography><Typography fontWeight={700}>{item?.availableUnits ?? 0} units</Typography><Typography variant="body2" color={item?.availabilityStatus === 'Out of Stock' ? 'error.main' : 'text.secondary'}>{item?.availabilityStatus ?? 'Out of Stock'}</Typography></CardContent></Card></Grid>; })}</Grid>}<Card sx={{ mt: 4, maxWidth: 600 }}><CardContent><Typography variant="h6">Request blood</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 2 }}><TextField select label="Blood group" value={group} onChange={(e) => setGroup(e.target.value)} fullWidth>{groups.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField><TextField label="Units" type="number" inputProps={{ min: 1, max: 20 }} value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} fullWidth /></Stack>{selected && <Typography variant="caption" display="block" sx={{ mt: 1 }}>{selected.availableUnits} units currently available.</Typography>}<Button sx={{ mt: 2 }} variant="contained" disabled={!group || quantity < 1 || (selected?.availableUnits ?? 0) < quantity} onClick={submit}>Request blood</Button></CardContent></Card></Container>; };
export default BloodBankPage;
