import { useEffect, useMemo, useState } from 'react';
import { Alert, Avatar, Box, Button, Card, CardActions, CardContent, Chip, Container, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Stack, TextField, Typography } from '@mui/material';
import EventAvailableIcon from '@mui/icons-material/EventAvailable';
import PersonIcon from '@mui/icons-material/Person';
import { bookAppointment, Doctor, getDoctors, getDoctorSchedule, AppointmentSlot } from '../services/doctors';
import { EmptyState, LoadingState } from '../components/PageState';

const dateValue = () => new Date().toISOString().slice(0, 10);

const DoctorsPage = () => {
  const [doctors, setDoctors] = useState<Doctor[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [selected, setSelected] = useState<Doctor | null>(null); const [date, setDate] = useState(dateValue()); const [slots, setSlots] = useState<AppointmentSlot[]>([]); const [slotLoading, setSlotLoading] = useState(false); const [booking, setBooking] = useState(false); const [success, setSuccess] = useState('');
  useEffect(() => { getDoctors().then((r) => setDoctors(r.data)).catch(() => setError('Unable to load doctors. Please try again later.')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) return; setSlotLoading(true); setSuccess(''); getDoctorSchedule(selected.id, date).then((r) => setSlots(r.data)).catch(() => setError('Unable to load this schedule.')).finally(() => setSlotLoading(false)); }, [selected, date]);
  const doctorName = (doctor: Doctor) => `Dr. ${doctor.user.firstName} ${doctor.user.lastName}`;
  const appointmentDateMin = useMemo(() => dateValue(), []);
  const chooseSlot = async (slot: AppointmentSlot) => { if (!selected || !slot.available) return; setBooking(true); setError(''); try { await bookAppointment(selected.id, slot.appointmentTime); setSuccess(`Appointment booked for ${new Date(slot.appointmentTime).toLocaleString()}.`); setSlots((old) => old.map((item) => item.appointmentTime === slot.appointmentTime ? { ...item, available: false } : item)); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to complete the booking. Please try again.'); } finally { setBooking(false); } };
  if (loading) return <Container maxWidth="lg"><LoadingState label="Loading doctors…" /></Container>;
  return <Container maxWidth="lg" sx={{ py: 5 }}><Typography variant="h4" component="h1">Find a doctor</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Browse hospital-managed doctor profiles and select a real available appointment slot.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{doctors.length === 0 ? <EmptyState>There are no doctor profiles configured yet. Please contact the hospital for an appointment.</EmptyState> : <Grid container spacing={3}>{doctors.map((doctor) => <Grid item xs={12} md={6} key={doctor.id}><Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}><CardContent sx={{ flexGrow: 1 }}><Stack direction="row" spacing={2}><Avatar sx={{ width: 58, height: 58, bgcolor: 'primary.light' }}><PersonIcon /></Avatar><Box><Typography variant="h6">{doctorName(doctor)}</Typography><Typography color="primary.main" fontWeight={600}>{doctor.specialization || 'Specialization not provided'}</Typography><Typography variant="body2" color="text.secondary">Department details and qualifications are provided by the hospital when available.</Typography></Box></Stack><Stack direction="row" spacing={1} sx={{ mt: 2 }}><Chip size="small" label={doctor.availability || 'Schedule available on request'} /></Stack></CardContent><CardActions><Button startIcon={<EventAvailableIcon />} onClick={() => setSelected(doctor)}>Book appointment</Button><Button onClick={() => setSelected(doctor)}>View schedule</Button></CardActions></Card></Grid>)}</Grid>}<Dialog open={Boolean(selected)} onClose={() => setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>{selected && doctorName(selected)} — schedule</DialogTitle><DialogContent><TextField label="Appointment date" type="date" value={date} onChange={(e) => setDate(e.target.value)} inputProps={{ min: appointmentDateMin }} InputLabelProps={{ shrink: true }} fullWidth sx={{ my: 2 }} />{success && <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert>}{slotLoading ? <LoadingState label="Checking available slots…" /> : <Grid container spacing={1}>{slots.map((slot) => <Grid item xs={6} sm={4} key={slot.appointmentTime}><Button fullWidth variant={slot.available ? 'outlined' : 'text'} disabled={!slot.available || booking} onClick={() => chooseSlot(slot)}>{new Date(slot.appointmentTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{!slot.available && ' · Unavailable'}</Button></Grid>)}</Grid>}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog></Container>;
};
export default DoctorsPage;
