import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardActions, CardContent, Chip, Container, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Stack, TextField, Typography } from '@mui/material';
import BiotechIcon from '@mui/icons-material/Biotech';
import { bookTest, DiagnosticTest, getTests } from '../services/portal';
import { EmptyState, LoadingState } from '../components/PageState';

const TestsPage = () => { const [tests, setTests] = useState<DiagnosticTest[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<DiagnosticTest | null>(null); const [time, setTime] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { getTests().then((r) => setTests(r.data)).catch(() => setError('Unable to load diagnostic tests.')).finally(() => setLoading(false)); }, []);
  const submit = async () => { if (!selected || !time) return; try { await bookTest(selected.id, time); setSuccess('Test slot booked successfully. It will appear in your profile.'); } catch (err: any) { setError(err?.response?.data?.message || 'Unable to book this test slot.'); } };
  if (loading) return <Container maxWidth="lg"><LoadingState label="Loading diagnostic tests…" /></Container>;
  return <Container maxWidth="lg" sx={{ py: 5 }}><Stack direction="row" spacing={1} alignItems="center"><BiotechIcon color="primary" /><Typography variant="h4" component="h1">Book a diagnostic test</Typography></Stack><Typography color="text.secondary" sx={{ mb: 3 }}>Only hospital-configured tests and available slots can be booked.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{tests.length === 0 ? <EmptyState>No diagnostic tests are currently configured. Please contact the hospital laboratory.</EmptyState> : <Grid container spacing={3}>{tests.map((test) => <Grid item xs={12} md={6} key={test.id}><Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}><CardContent sx={{ flexGrow: 1 }}><Chip size="small" label={test.category} color="primary" variant="outlined" /><Typography variant="h6" sx={{ mt: 1 }}>{test.name}</Typography><Typography variant="body2" color="text.secondary">{test.description || 'Description will be provided by the hospital laboratory.'}</Typography><Typography variant="body2" sx={{ mt: 2 }}><b>Preparation:</b> {test.preparationInstructions || 'No preparation instructions provided.'}</Typography><Typography variant="body2"><b>Processing:</b> {test.estimatedProcessingTime || 'To be confirmed by the laboratory.'}</Typography></CardContent><CardActions><Button onClick={() => { setSelected(test); setSuccess(''); }}>Book test</Button></CardActions></Card></Grid>)}</Grid>}<Dialog open={Boolean(selected)} onClose={() => setSelected(null)} fullWidth maxWidth="xs"><DialogTitle>Book {selected?.name}</DialogTitle><DialogContent><TextField label="Date and time" type="datetime-local" InputLabelProps={{ shrink: true }} inputProps={{ min: new Date().toISOString().slice(0, 16) }} value={time} onChange={(e) => setTime(e.target.value)} fullWidth sx={{ mt: 1 }} />{success && <Alert severity="success" sx={{ mt: 2 }}>{success}</Alert>}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button><Button variant="contained" disabled={!time} onClick={submit}>Confirm booking</Button></DialogActions></Dialog></Container>; };
export default TestsPage;
